// React types
export const DFS_GET_VOTER_PENDING = 'DFS_GET_VOTER_PENDING';
export const DFS_GET_VOTER_SUCCESS = 'DFS_GET_VOTER_SUCCESS';
export const DFS_GET_VOTER_FAILURE = 'DFS_GET_VOTER_FAILURE';

export const DFS_GET_LIQ_PENDING = 'DFS_GET_LIQ_PENDING';
export const DFS_GET_LIQ_SUCCESS = 'DFS_GET_LIQ_SUCCESS';
export const DFS_GET_LIQ_FAILURE = 'DFS_GET_LIQ_FAILURE';

export const DFS_GET_MARKETS_PENDING = 'DFS_GET_MARKETS_PENDING';
export const DFS_GET_MARKETS_SUCCESS = 'DFS_GET_MARKETS_SUCCESS';
export const DFS_GET_MARKETS_FAILURE = 'DFS_GET_MARKETS_FAILURE';

export const DFS_GET_VOTE_PENDING = 'DFS_GET_VOTE_PENDING';
export const DFS_GET_VOTE_SUCCESS = 'DFS_GET_VOTE_SUCCESS';
export const DFS_GET_VOTE_FAILURE = 'DFS_GET_VOTE_FAILURE';

export const DFS_SWITCH_SMOOTH_MODE = 'DFS_SWITCH_SMOOTH_MODE';

